// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RouteAPI.Data;
using System;

namespace RouteAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RouteAPI.Models.Car", b =>
                {
                    b.Property<string>("carCode")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("driverName")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("status")
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("carCode");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
